/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonCancel: typeof import('./src/components/inputs/ButtonCancel.vue')['default']
    ButtonPrimary: typeof import('./src/components/inputs/ButtonPrimary.vue')['default']
    ButtonValidate: typeof import('./src/components/inputs/ButtonValidate.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CardModal: typeof import('./src/components/CardModal.vue')['default']
    copy: typeof import('./src/fragments/NewCardNoNFC copy.vue')['default']
    IconButton: typeof import('./src/components/inputs/IconButton.vue')['default']
    ItemButton: typeof import('./src/components/inputs/ItemButton.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NewCardModal: typeof import('./src/fragments/NewCardModal.vue')['default']
    NewCardNFC: typeof import('./src/fragments/NewCardNFC.vue')['default']
    NewCardNoNFC: typeof import('./src/fragments/NewCardNoNFC.vue')['default']
    OrgaPage: typeof import('./src/components/OrgaPage.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/inputs/TextInput.vue')['default']
    ValidateModal: typeof import('./src/components/ValidateModal.vue')['default']
  }
}
